services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  shortener:
    build: ./shortener-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIRECT_BASE_URL: "http://localhost:3000"
    ports:
      - "5001:5000"
    depends_on:
      - redis

  redirector:
    build: ./redirect-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "3000:3000"
    depends_on:
      - redis
